#!/usr/bin/env python3
"""Extract the NSS increment of kuncy7/openwrt-nss-edma into a vendored overlay.

Reproduces, on top of a pinned official OpenWrt base commit, the exact tree
state of the kuncy7 c3po-tag-8021q branch. The overlay is a plain directory
of files plus a manifest; applying it (see ../apply-nss-overlay.sh) yields a
tree that is byte-identical to the kuncy7 branch — verified here per file by
git hash-object equality with the branch blobs.

Requirements: a local clone of kuncy7/openwrt-nss-edma (or any git repo that
contains BOTH object ids below — the kuncy7 repo mirrors git.openwrt.org, so
the official base commit can be fetched into it by SHA:

    git fetch --depth 1 origin <BASE_SHA>

Usage:
    python3 extract-nss-overlay.py <kuncy7-repo-dir> <overlay-dir>

Writes:
    <overlay-dir>/tree/<path>   vendored file contents (A and M entries)
    <overlay-dir>/MANIFEST.txt  A/M/D/L entries with sha256 preconditions

Then copy this script to <overlay-dir>/tools/extract-nss-overlay.py to keep
the derivation reproducible.
"""

import hashlib
import os
import subprocess
import sys

# Pinned provenance. BASE is an official openwrt/openwrt commit (verify at
# https://github.com/openwrt/openwrt/commit/<BASE>); HEAD is the kuncy7
# branch tip the overlay was extracted from.
BASE = "3ab520425b127d66617bfeb1e2805b4f20109f95"  # openwrt main, 2026-09-25
HEAD = "2f00ddefdba6b31d21f8b1d0edeb782c4eac5d6e"  # kuncy7 c3po-tag-8021q


def main():
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    repo, overlay = sys.argv[1], sys.argv[2]

    def git(*args, binary=False):
        r = subprocess.run(["git", "-C", repo, *args], capture_output=True)
        if r.returncode != 0:
            sys.exit("git %s failed: %s" % (" ".join(args), r.stderr.decode(errors="replace")))
        return r.stdout if binary else r.stdout.decode("utf-8", errors="replace")

    for sha, what in ((BASE, "base"), (HEAD, "head")):
        if git("cat-file", "-t", sha).strip() != "commit":
            sys.exit("commit %s (%s) not in %s — git fetch --depth 1 origin %s" % (sha, what, repo, sha))

    raw = git("diff-tree", "-r", "--no-renames", "--no-abbrev", BASE, HEAD)
    entries = []
    for line in raw.splitlines():
        meta, path = line.split("\t", 1)
        f = meta.split(" ")
        old_mode, new_mode, old_sha, new_sha, status = f[0][1:], f[1], f[2], f[3], f[4]
        if " " in path or path.startswith("/"):
            sys.exit("unexpected path: %r" % path)
        entries.append(dict(st=status, om=old_mode, nm=new_mode,
                            os_=old_sha, ns=new_sha, path=path))

    tree_dir = os.path.join(overlay, "tree")
    for e in entries:
        if e["st"] not in ("A", "M", "D"):
            sys.exit("unexpected diff status %r for %s (rename detection must be off)" % (e["st"], e["path"]))

    def blob_bytes(sha):
        return git("cat-file", "blob", sha, binary=True)

    lines = []
    n = {"A": 0, "M": 0, "D": 0, "L": 0}
    for e in sorted(entries, key=lambda x: x["path"]):
        path, st = e["path"], e["st"]
        if e["nm"] == "120000":  # symlink in the branch
            target = blob_bytes(e["ns"]).decode()
            if " " in target or not target:
                sys.exit("unexpected symlink target %r for %s" % (target, path))
            lines.append("L - %s 120000 %s" % (target, path))
            n["L"] += 1
            continue
        new_b = blob_bytes(e["ns"]) if st in ("A", "M") else None
        base_b = blob_bytes(e["os_"]) if st in ("M", "D") else None
        if st in ("A", "M"):
            dest = os.path.join(tree_dir, *path.split("/"))
            os.makedirs(os.path.dirname(dest), exist_ok=True)
            with open(dest, "wb") as fh:
                fh.write(new_b)
            # byte-fidelity proof: git hash-object of the written file must
            # equal the branch blob id
            r = subprocess.run(["git", "-C", repo, "hash-object", dest], capture_output=True, text=True)
            if r.stdout.strip() != e["ns"]:
                sys.exit("hash-object mismatch for %s: %s != %s" % (path, r.stdout.strip(), e["ns"]))
        new_h = hashlib.sha256(new_b).hexdigest() if new_b else "-"
        if st == "A":
            lines.append("A - %s %s %s" % (new_h, e["nm"], path))
        elif st == "M":
            base_h = hashlib.sha256(base_b).hexdigest()
            lines.append("M %s %s %s %s" % (base_h, new_h, e["nm"], path))
        else:
            base_h = hashlib.sha256(base_b).hexdigest()
            lines.append("D %s - - %s" % (base_h, path))
        n[st] += 1

    manifest = os.path.join(overlay, "MANIFEST.txt")
    with open(manifest, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# NSS overlay manifest (generated by tools/extract-nss-overlay.py)\n")
        fh.write("# base:  openwrt/openwrt %s (official main, 2026-09-25)\n" % BASE)
        fh.write("# head:  kuncy7/openwrt-nss-edma c3po-tag-8021q %s\n" % HEAD)
        fh.write("# format: <st> <sha256_base|-> <sha256_new|target|-> <mode_new|-> <path>\n")
        fh.write("#   M modify  A add  D delete  L symlink (2nd field '-', 3rd = link target)\n")
        fh.write("#   M/D carry the base sha256 as a precondition: apply-nss-overlay.sh\n")
        fh.write("#   refuses to run on any tree whose files do not match the pinned base.\n")
        fh.write("\n".join(lines) + "\n")
    print("entries: %d (A %d, M %d, D %d, L %d) -> %s" % (len(entries), n["A"], n["M"], n["D"], n["L"], manifest))


if __name__ == "__main__":
    main()
