#!/bin/sh
#
# File: diy/cr8806/nss-overlay/apply-nss-overlay.sh
# Description: Apply the vendored NSS overlay (MANIFEST.txt + tree/) onto an
#              extracted official OpenWrt base tree, reproducing the
#              kuncy7/openwrt-nss-edma c3po-tag-8021q source state.
#
# The manifest was generated by tools/extract-nss-overlay.py from:
#   base: openwrt/openwrt 3ab520425b127d66617bfeb1e2805b4f20109f95 (official main)
#   head: kuncy7/openwrt-nss-edma c3po-tag-8021q 2f00ddefdba6b31d21f8b1d0edeb782c4eac5d6e
#
# Three passes over the manifest:
#   1. preconditions — every M/D file in the target tree must still match the
#      pinned base sha256, so the script fails loudly if the base commit is
#      changed without re-deriving the overlay;
#   2. apply — copy A/M files from tree/, remove D files, create L symlinks,
#      set executable bits where the branch has them;
#   3. verify — every applied file must hash to the recorded sha256, every
#      removed file must be gone, every symlink must resolve to its target.
#
# The per-file content fidelity of tree/ was already proven at extraction
# time (git hash-object == branch blob id), so a green verify pass means the
# result is byte-identical to the kuncy7 branch.
#
# Usage: apply-nss-overlay.sh <openwrt-tree-dir>   (default: current dir)
#
# This is free software, licensed under the MIT License.
#

set -eu

OVERLAY_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
MANIFEST="$OVERLAY_DIR/MANIFEST.txt"
SRC="$OVERLAY_DIR/tree"
TREE=${1:-.}

[ -f "$MANIFEST" ] || { echo "apply-nss-overlay: MANIFEST.txt not found" >&2; exit 1; }
cd "$TREE"
[ -d target/linux ] && [ -f feeds.conf.default ] || {
    echo "apply-nss-overlay: '$TREE' does not look like an OpenWrt source tree" >&2
    exit 1
}

sha() { sha256sum "$1" | cut -d' ' -f1; }

# --- pass 1: preconditions ----------------------------------------------------
pre_fail=0
pre_n=0
while IFS=' ' read -r st base new mode path; do
    case "$st" in '#'*) continue ;; esac
    [ -n "$st" ] || continue
    case "$st" in
    M|D)
        pre_n=$((pre_n + 1))
        if [ ! -f "$path" ]; then
            echo "::error::[pre] $st $path: present in the pinned base, missing here" >&2
            pre_fail=1
            continue
        fi
        got=$(sha "$path")
        if [ "$got" != "$base" ]; then
            echo "::error::[pre] $path: sha256 $got != pinned base $base" >&2
            echo "::error::the tree is not the pinned official base — re-derive the overlay (see tools/extract-nss-overlay.py)" >&2
            pre_fail=1
        fi
        ;;
    esac
done < "$MANIFEST"
[ "$pre_fail" -eq 0 ] || { echo "apply-nss-overlay: $pre_n preconditions checked, FAILED" >&2; exit 1; }
echo "apply-nss-overlay: preconditions ok ($pre_n files match the pinned base)"

# --- pass 2: apply ------------------------------------------------------------
n_add=0; n_mod=0; n_del=0; n_link=0
while IFS=' ' read -r st base new mode path; do
    case "$st" in '#'*) continue ;; esac
    [ -n "$st" ] || continue
    case "$st" in
    A|M)
        mkdir -p "$(dirname -- "$path")"
        cp -f "$SRC/$path" "$path"
        [ "$mode" = 100755 ] && chmod +x "$path" || true
        case "$st" in A) n_add=$((n_add + 1)) ;; M) n_mod=$((n_mod + 1)) ;; esac
        ;;
    D)
        rm -f "$path"
        n_del=$((n_del + 1))
        ;;
    L)
        mkdir -p "$(dirname -- "$path")"
        rm -f "$path"
        ln -s "$new" "$path"
        n_link=$((n_link + 1))
        ;;
    *)
        echo "::error::manifest line not understood: $st $path" >&2
        exit 1
        ;;
    esac
done < "$MANIFEST"
echo "apply-nss-overlay: applied $n_add added, $n_mod modified, $n_del removed, $n_link linked"

# --- pass 3: verify -----------------------------------------------------------
ver_fail=0
while IFS=' ' read -r st base new mode path; do
    case "$st" in '#'*) continue ;; esac
    [ -n "$st" ] || continue
    case "$st" in
    A|M)
        got=$(sha "$path" 2>/dev/null || echo missing)
        [ "$got" = "$new" ] || { echo "::error::[verify] $path: sha256 $got != expected $new" >&2; ver_fail=1; }
        if [ "$mode" = 100755 ] && [ ! -x "$path" ]; then
            echo "::error::[verify] $path: expected executable bit" >&2; ver_fail=1
        fi
        ;;
    D)
        [ ! -e "$path" ] || { echo "::error::[verify] $path: still present after removal" >&2; ver_fail=1; }
        ;;
    L)
        [ "$(readlink "$path" 2>/dev/null || echo none)" = "$new" ] || {
            echo "::error::[verify] $path: readlink '$(readlink "$path" 2>/dev/null)' != '$new'" >&2; ver_fail=1; }
        ;;
    esac
done < "$MANIFEST"
[ "$ver_fail" -eq 0 ] || { echo "apply-nss-overlay: verification FAILED" >&2; exit 1; }

echo "apply-nss-overlay: verified — tree now reproduces kuncy7 c3po-tag-8021q 2f00ddefdba6b31d21f8b1d0edeb782c4eac5d6e on official base 3ab520425b127d66617bfeb1e2805b4f20109f95"
